- name: Reset nginx module
  ansible.builtin.command:
    cmd: dnf module reset nginx -y

- name: Enable nginx 1.24 module
  ansible.builtin.command:
    cmd: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

# - name: Find default nginx content
#   ansible.builtin.find:
#     paths: /usr/share/nginx/html
#   register: nginx_html_files

- name: Remove default nginx content
  ansible.builtin.file:
    path: "{{ path }}"
    state: absent
  

- name: Extract frontend files
  ansible.builtin.unarchive:
    src: "{{url}}"
    dest: /tmp/
    remote_src: yes

- name: Configuring the hostName
  ansible.builtin.command: set-hostname frontend-{{env}}



    