- name: Reset nginx module
  ansible.builtin.command:
    cmd: dnf module reset nginx -y

- name: Enable nginx 1.24 module
  ansible.builtin.command:
    cmd: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
    
- name: starting nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true