- name: Reset "{{packagename}}" module
  ansible.builtin.command:
    cmd: dnf module reset "{{packagename}}" -y

- name: Enable "{{packagename}}" 1.24 module
  ansible.builtin.command:
    cmd: dnf module enable "{{packagename}}":1.24 -y

- name: Install "{{packagename}}"
  ansible.builtin.package:
    name: "{{packagename}}"
    state: present



# - name: Find default "{{packagename}}" content
#   ansible.builtin.find:
#     paths: /usr/share/"{{packagename}}"/html
#   register: "{{packagename}}"_html_files

- name: Remove default "{{packagename}}" content
  ansible.builtin.file:
    path: "{{ path }}"
    state: absent

- name: Probsing "{{packagename}}" content
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory


- name: Extract frontend files
  ansible.builtin.unarchive:
    src: "{{url}}"
    dest: /usr/share/"{{packagename}}"/html
    remote_src: yes

- name: updating the ngnix config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    remote_src: yes

- name: Start "{{packagename}}"
  ansible.builtin.service:
    name: "{{packagename}}"
    state: started
    enabled: true

- name: Configuring the hostName
  ansible.builtin.command: set-hostname frontend-{{env}}



    